add: pw reset

diff --git a/.github/workflows/kubernetes-resource-management.yml b/.github/workflows/kubernetes-resource-management.yml
--- a/.github/workflows/kubernetes-resource-management.yml
+++ b/.github/workflows/kubernetes-resource-management.yml
@@ -64,14 +64,27 @@ jobs:
         helm repo update
         kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
         helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --debug || echo "Failed to install Prometheus"
-        helm upgrade --install grafana grafana/grafana --namespace monitoring \
-          --set adminUser="${GRAFANA_ADMIN_USER}" \
-          --set adminPassword="${GRAFANA_ADMIN_PASSWORD}" --debug || echo "Failed to install Grafana"
+        helm upgrade --install grafana grafana/grafana --namespace monitoring --debug || echo "Failed to install Grafana"
         
         echo "Verifying Prometheus installation:"
         kubectl get pods -n monitoring -l app=prometheus
         echo "Verifying Grafana installation:"
         kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana
+
+    - name: Reset Grafana admin password
+      run: |
+        GRAFANA_POD=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath="{.items[0].metadata.name}")
+        echo "Grafana pod name: $GRAFANA_POD"
+        
+        kubectl exec -it -n monitoring $GRAFANA_POD -- \
+          grafana-cli --homepath "/usr/share/grafana" admin reset-admin-password "${GRAFANA_ADMIN_PASSWORD}"
+        
+        if [ $? -eq 0 ]; then
+          echo "Grafana admin password reset successfully"
+        else
+          echo "Failed to reset Grafana admin password"
+          kubectl logs -n monitoring $GRAFANA_POD
+        fi
 
     - name: Install or update Logging resources
       run: |
